version: "3"
services:
        nginx:
                image: nginx
                ports:
                        - 80:80
                volumes:
                        - ./docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
                        - ./:/app
        php:
                build: .
                working_dir: /app
                volumes:
                        - ./:/app
        mysql:
                image: mysql:5
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: homestead
                        MYSQL_USER: homestead
                        MYSQL_PASSWORD: secret
